export const applicationsData = [
  {
    id: "1",
    companyName: "Startup Inc",
    role: "Part-time Developer",
    type: "Part-time",
    status: "Applied",
    date: "Jun 12, 2026",
  },
  {
    id: "2",
    companyName: "Airbnb",
    role: "React Developer",
    type: "Full-time",
    status: "Interviewing",
    date: "May 25, 2026",
  },
  {
    id: "3",
    companyName: "Netflix",
    role: "Senior Engineer",
    type: "Full-time",
    status: "Applied",
    date: "Jun 10, 2026",
  },
  {
    id: "4",
    companyName: "Shopify",
    role: "Full Stack Intern",
    type: "Internship",
    status: "Rejected",
    date: "Mar 10, 2026",
  },
  {
    id: "5",
    companyName: "Stripe",
    role: "Backend Engineer",
    type: "Full-time",
    status: "Offer",
    date: "Apr 15, 2026",
  },
  {
    id: "6",
    companyName: "Meta",
    role: "Frontend Developer",
    type: "Full-time",
    status: "Applied",
    date: "Jun 1, 2026",
  },
  {
    id: "7",
    companyName: "Google",
    role: "Software Engineer",
    type: "Full-time",
    status: "Interviewing",
    date: "May 20, 2026",
  },
];
